name: Automatic Versioning
author: discoverygarden
description: Updates the current version tag based on a provided label.

inputs:
  token:
    description: 'Token to use to push to the repo. Pass in using `secrets.GITHUB_TOKEN`.'
    required: false
    default: ${{ github.token }}
  prefix:
    description: The prefix prepended to the version number. Default is v.
    required: false
    default: v
outputs:
  tag:
    description: 'The version string used to create the tag.'
    value: ${{ steps.tag.outputs.version_tag }}

runs:
  using: "composite"
  steps:
    - id: bump
      # match-label-action:v5
      uses: zwaldowski/match-label-action@74600601f0f19eeede58634e04b3cc5188a0d7c3
      with:
        allowed: major,minor,patch
    - id: tag
      # semver-release-action:v4
      uses: zwaldowski/semver-release-action@a6a8309186ccf60c52ea2463a723c78d3b924577
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ inputs.token }}
        prefix: ${{ inputs.prefix }}
